#!/usr/bin/env python3
"""Commit manifest-listed files and push the feature branch.

Usage: python3 commit.py <ticket-id> --base-path <path> [--repo-path <path>] [--draft]
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def git(*args, cwd=None):
    r = subprocess.run(["git", *args], capture_output=True, text=True, cwd=cwd)  # noqa: S603 S607
    return r.returncode, r.stdout.strip(), r.stderr.strip()


def write_json(path, data):
    path.write_text(json.dumps(data, indent=2) + "\n")


def fail(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ticket", help="JIRA ticket ID")
    parser.add_argument("--base-path", required=True)
    parser.add_argument("--repo-path", default="")
    parser.add_argument("--draft", action="store_true")
    args = parser.parse_args()

    ticket = args.ticket.upper()
    base = Path(args.base_path)
    out = base / "commit"
    out.mkdir(parents=True, exist_ok=True)
    cwd = args.repo_path or None

    empty_info = {"branch": None, "commit_sha": None, "files_committed": [],
                  "platform": None, "repo_url": None, "pushed": False}

    def step_result(sha=None, branch=None, pushed=False, skipped=False, reason=None):
        return {"schema_version": 1, "step": "commit", "ticket": ticket,
                "completed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "commit_sha": sha, "branch": branch, "pushed": pushed,
                "skipped": skipped, "skip_reason": reason}

    # Draft mode — skip
    if args.draft:
        write_json(out / "commit-info.json", empty_info)
        write_json(out / "step-result.json", step_result(skipped=True, reason="draft"))
        print("Draft mode — skipped committing.")
        return

    # Resolve git context
    rc, repo_dir, err = git("rev-parse", "--show-toplevel", cwd=cwd)
    if rc != 0:
        fail(f"Not a git repository: {err}")
    rc, branch, err = git("rev-parse", "--abbrev-ref", "HEAD", cwd=cwd)
    if rc != 0:
        fail(f"Could not determine branch: {err}")
    rc, repo_url, err = git("remote", "get-url", "origin", cwd=cwd)
    if rc != 0:
        fail(f"Could not get remote URL: {err}")

    platform = "github" if "github.com" in repo_url.lower() else (
        "gitlab" if "gitlab" in repo_url.lower() else "unknown")

    if branch in ("main", "master"):
        fail(f"Refusing to push to '{branch}'.")

    # Read manifest from writing step sidecar
    sidecar = base / "writing" / "step-result.json"
    if not sidecar.exists():
        print("No writing step-result.json found — nothing to commit.")
        write_json(out / "commit-info.json", {**empty_info, "branch": branch,
                   "platform": platform, "repo_url": repo_url})
        write_json(out / "step-result.json", step_result(branch=branch, skipped=True, reason="no_changes"))
        return

    repo_prefix = str(Path(repo_dir).resolve())
    files = [f for f in json.loads(sidecar.read_text()).get("files", [])
             if f.startswith(repo_prefix)]
    if not files:
        print(f"No files in manifest under {repo_prefix}.")
        write_json(out / "commit-info.json", {**empty_info, "branch": branch,
                   "platform": platform, "repo_url": repo_url})
        write_json(out / "step-result.json", step_result(branch=branch, skipped=True, reason="no_changes"))
        return

    # Stage files
    staged = []
    for f in files:
        if not Path(f).is_file():
            print(f"WARNING: {f} not found, skipping.", file=sys.stderr)
            continue
        rc, _, err = git("add", f, cwd=repo_dir)
        if rc != 0:
            print(f"WARNING: failed to stage {f}: {err}", file=sys.stderr)
            continue
        staged.append(f.removeprefix(repo_prefix + "/") if f.startswith(repo_prefix) else f)

    rc, _, _ = git("diff", "--cached", "--quiet", cwd=repo_dir)
    if not staged or rc == 0:
        print("No changes to commit.")
        write_json(out / "commit-info.json", {**empty_info, "branch": branch,
                   "platform": platform, "repo_url": repo_url})
        write_json(out / "step-result.json", step_result(branch=branch, skipped=True, reason="no_changes"))
        return

    # Commit
    file_list = "\n".join(f"  - {f}" for f in staged)
    msg = (f"docs({ticket.lower()}): add generated documentation\n\n"
           f"Files:\n{file_list}\n\nGenerated by docs-pipeline for {ticket}")
    rc, commit_out, err = git("commit", "-m", msg, cwd=repo_dir)
    if rc != 0:
        fail(f"git commit failed: {err}")
    print(commit_out)

    _, sha, _ = git("rev-parse", "HEAD", cwd=repo_dir)

    # Push
    git("fetch", "origin", branch, cwd=repo_dir)
    rc, _, err = git("push", "--force-with-lease", "-u", "origin", branch, cwd=repo_dir)
    if rc != 0:
        print(f"ERROR: Push failed: {err}", file=sys.stderr)
        write_json(out / "commit-info.json", {"branch": branch, "commit_sha": sha,
                   "files_committed": staged, "platform": platform, "repo_url": repo_url, "pushed": False})
        write_json(out / "step-result.json", step_result(sha, branch, pushed=False))
        sys.exit(1)

    print(f"Pushed {branch} ({sha})")
    write_json(out / "commit-info.json", {"branch": branch, "commit_sha": sha,
               "files_committed": staged, "platform": platform, "repo_url": repo_url, "pushed": True})
    write_json(out / "step-result.json", step_result(sha, branch, pushed=True))


if __name__ == "__main__":
    main()
